on:
  push:
    branches:
      - 'master'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm run test

      - name: Upload eslint-v9-js coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/eslint-v9-js/coverage/coverage-final.json
          flags: eslint-v9-js
          token: ${{ secrets.CODECOV_TOKEN }}
