on:
  push:
    branches:
      - 'master'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test
